# Wallpaper Slideshow: downloads the Bing picture of the day and cycles them every 10 minutes.

[org/gnome/shell/extensions/azwallpaper]
bing-download-directory=@BING_DIR@
bing-wallpaper-download=true
bing-wallpaper-download-count=8
bing-wallpaper-market='ja-JP'
bing-wallpaper-notify-on-error=true
bing-wallpaper-resolution=@BING_RESOLUTION@
slideshow-directory=@BING_DIR@
slideshow-pause-notifications=false
slideshow-pause-on-fullscreen=true
slideshow-slide-duration=(0, 10, 0)
slideshow-use-absolute-time-for-duration=true
update-notifier-project-version=@AZWALLPAPER_VERSION@
