# Blur my Shell: frosted top bar, dock, overview, popups and lock screen.

[org/gnome/shell/extensions/blur-my-shell]
hacks-level=2
pipelines={'pipeline_default': {'name': <'Default'>, 'effects': <[<{'type': <'refraction'>, 'id': <'effect_02518859522117'>, 'params': <{'blur_radius': <10>, 'corner_radius': <0>, 'tint': <0>}>}>, <{'type': <'color'>, 'id': <'effect_13572789429906'>, 'params': <{'color': <(0.0, 0.0, 0.0, 0.63999998569488525)>, 'blend_mode': <4>}>}>]>}}
settings-version=2

[org/gnome/shell/extensions/blur-my-shell/appfolder]
brightness=0.40000000000000002
sigma=10
style-dialogs=3

[org/gnome/shell/extensions/blur-my-shell/applications]
blur=false
blur-on-overview=true
brightness=0.29999999999999999
corner-radius=22
corner-when-maximized=false
dynamic-opacity=true
enable-all=true
opacity=210
pipeline='pipeline_default'
sigma=10
static-blur=false
unblur-when-fullscreen=true

[org/gnome/shell/extensions/blur-my-shell/coverflow-alt-tab]
blur=true
pipeline='pipeline_default'

[org/gnome/shell/extensions/blur-my-shell/dash-to-dock]
blur=true
brightness=0.69999999999999996
corner-radius=20
override-background=false
pipeline='pipeline_default'
sigma=8
static-blur=false
style-dash-to-dock=0
unblur-in-overview=true

[org/gnome/shell/extensions/blur-my-shell/hidetopbar]
compatibility=false

[org/gnome/shell/extensions/blur-my-shell/lockscreen]
pipeline='pipeline_default'

[org/gnome/shell/extensions/blur-my-shell/overview]
blur=true
pipeline='pipeline_default'
style-components=3

[org/gnome/shell/extensions/blur-my-shell/panel]
brightness=0.69999999999999996
corner-radius=0
force-light-text=false
pipeline='pipeline_default'
sigma=5
static-blur=false
unblur-in-overview=true

[org/gnome/shell/extensions/blur-my-shell/popup]
blur=true
brightness=0.80000000000000004
corner-radius=20
dialog-corner-radius=20
menu-corner-radius=20
notification-corner-radius=20
osd-corner-radius=20
osk-corner-radius=20
override-background=true
pipeline='pipeline_default'
quick-settings-corner-radius=20
sigma=12

[org/gnome/shell/extensions/blur-my-shell/screenshot]
pipeline='pipeline_default'

[org/gnome/shell/extensions/blur-my-shell/window-list]
blur=true
brightness=0.5
sigma=10
