# Clipboard Indicator: clipboard history (Super+V).

[org/gnome/shell/extensions/clipboard-indicator]
blink-icon-on-copy=true
cache-only-favorites=true
cache-size=32
clear-history=['<Super>BackSpace']
disable-down-arrow=true
display-mode=0
history-size=50
next-entry=@as []
next-history-clear=-1
prev-entry=@as []
private-mode-binding=@as []
toggle-menu=['<Super>v']
topbar-preview-size=1
