# Global Menu: app menu bar in the top bar.

[org/gnome/shell/extensions/globalmenu]
custom-menus='[]'
desktop-app-name='Files'
extensions-app-id=@EXTENSIONS_APP@
hide-overview-button=true
logo-custom-icon-path=''
logo-distro-icon='apple'
logo-distro-icon-symbolic=true
logo-icon-size=20
menu-app-enabled=true
menu-edit-enabled=false
menu-file-enabled=false
menu-go-enabled=false
menu-help-enabled=false
menu-view-enabled=false
show-app-grid=true
show-indicator=true
show-lock-screen=true
show-logo-menu=false
show-power-options=true
show-software-center=true
software-center-command=@SOFTWARE_CMD@
terminal-command=@TERMINAL_CMD@
