# Medialine: now-playing media in the top bar.

[org/gnome/shell/extensions/medialine]
hide-default-notification=true
icon-size=14
icon-spacing=8
icon-type='album-art'
max-text-width=350
panel-index=16
panel-position='left'
popup-background-color=''
popup-dynamic-bg=false
popup-dynamic-bg-intensity=0.20000000000000001
popup-show-visualizer=false
show-album=false
