# Rounded Window Corners Reborn: rounded corners and soft shadows on every window.

[org/gnome/shell/extensions/rounded-window-corners-reborn]
blacklist=['fl64.exe']
border-width=3
custom-rounded-corner-settings=@a{sv} {}
focused-shadow={'verticalOffset': 4, 'horizontalOffset': 2, 'blurOffset': 20, 'spreadRadius': 18, 'opacity': 50}
global-rounded-corner-settings={'padding': <{'left': uint32 0, 'right': 0, 'top': 0, 'bottom': 0}>, 'keepRoundedCorners': <{'maximized': false, 'fullscreen': false}>, 'borderRadius': <uint32 22>, 'smoothing': <0.10000000000000001>, 'borderColor': <(0.25098040699958801, 0.25098040699958801, 0.25098040699958801, 0.43999999761581421)>, 'enabled': <true>}
keep-shadow-for-maximized-fullscreen=false
settings-version=uint32 9
skip-libadwaita-app=false
skip-libhandy-app=false
unfocused-shadow={'verticalOffset': 4, 'horizontalOffset': 2, 'blurOffset': 30, 'spreadRadius': 18, 'opacity': 40}
whitelist=false
