# Preferences of the core GNOME apps. Harmless where an app isn't installed.

[org/gnome/nautilus/list-view]
default-zoom-level='medium'
use-tree-view=true

[org/gnome/nautilus/preferences]
date-time-format='detailed'
default-folder-viewer='list-view'
show-create-link=true
show-delete-permanently=true

[org/gtk/gtk4/settings/file-chooser]
date-format='regular'
location-mode='path-bar'
show-hidden=false
sort-column='name'
sort-directories-first=true
sort-order='ascending'
type-format='category'
view-type='grid'

[org/gtk/settings/file-chooser]
date-format='regular'
location-mode='path-bar'
show-hidden=false
show-size-column=true
show-type-column=true
sort-column='name'
sort-directories-first=false
sort-order='ascending'
type-format='category'

[org/gnome/Ptyxis]
cursor-shape='ibeam'
default-profile-uuid='ef2101891f0b8f3ce592fe536ac4e9b8'
enable-a11y=false
interface-style='system'
new-tab-position='next'
profile-uuids=['ef2101891f0b8f3ce592fe536ac4e9b8']

[org/gnome/Ptyxis/Profiles/ef2101891f0b8f3ce592fe536ac4e9b8]
cell-height-scale=1.0
cell-width-scale=1.0
cjk-ambiguous-width='wide'
login-shell=false
palette='gnome'
preserve-directory='always'
scroll-on-output=true

[org/gnome/Console]
custom-font='Fira Code 10'
ignore-scrollback-limit=true
theme='auto'
use-system-font=false

[org/gnome/TextEditor]
highlight-current-line=true
right-margin-position=uint32 120
show-line-numbers=true
show-map=true
show-right-margin=true
style-scheme='Adwaita-dark'
tab-width=uint32 4
